export const HOME_FETCH_SHEETS_BEGIN = 'HOME_FETCH_SHEETS_BEGIN';
export const HOME_FETCH_SHEETS_SUCCESS = 'HOME_FETCH_SHEETS_SUCCESS';
export const HOME_FETCH_SHEETS_FAILURE = 'HOME_FETCH_SHEETS_FAILURE';
export const HOME_FETCH_SHEETS_DISMISS_ERROR = 'HOME_FETCH_SHEETS_DISMISS_ERROR';
